"""add access rule tracking to message traces

Revision ID: 0758c72b3e68
Revises: 49e3788203da
Create Date: 2025-10-22 13:20:21.523296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0758c72b3e68"
down_revision: Union[str, Sequence[str], None] = "49e3788203da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add access rule tracking fields to message_traces
    op.add_column("message_traces", sa.Column("blocked_by_access_rule", sa.Boolean(), nullable=True))
    op.add_column("message_traces", sa.Column("access_rule_id", sa.Integer(), nullable=True))
    op.add_column("message_traces", sa.Column("blocking_reason", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_message_traces_blocked_by_access_rule"), "message_traces", ["blocked_by_access_rule"], unique=False
    )
    op.create_foreign_key(None, "message_traces", "access_rules", ["access_rule_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove access rule tracking fields from message_traces
    op.drop_constraint(None, "message_traces", type_="foreignkey")
    op.drop_index(op.f("ix_message_traces_blocked_by_access_rule"), table_name="message_traces")
    op.drop_column("message_traces", "blocking_reason")
    op.drop_column("message_traces", "access_rule_id")
    op.drop_column("message_traces", "blocked_by_access_rule")
    # ### end Alembic commands ###
