"""initial_migration_with_all_tables

Revision ID: 30974a03f6b8
Revises: 
Create Date: 2025-11-27 00:58:11.414494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30974a03f6b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('validation_rules', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_settings_category'), 'global_settings', ['category'], unique=False)
    op.create_index(op.f('ix_global_settings_id'), 'global_settings', ['id'], unique=False)
    op.create_index(op.f('ix_global_settings_key'), 'global_settings', ['key'], unique=True)
    op.create_table('instance_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('evolution_url', sa.String(), nullable=True),
    sa.Column('evolution_key', sa.String(), nullable=True),
    sa.Column('whatsapp_instance', sa.String(), nullable=True),
    sa.Column('session_id_prefix', sa.String(), nullable=True),
    sa.Column('webhook_base64', sa.Boolean(), nullable=False),
    sa.Column('discord_bot_token', sa.String(), nullable=True),
    sa.Column('discord_client_id', sa.String(), nullable=True),
    sa.Column('discord_guild_id', sa.String(), nullable=True),
    sa.Column('discord_default_channel_id', sa.String(), nullable=True),
    sa.Column('discord_voice_enabled', sa.Boolean(), nullable=True),
    sa.Column('discord_slash_commands_enabled', sa.Boolean(), nullable=True),
    sa.Column('discord_webhook_url', sa.String(), nullable=True),
    sa.Column('discord_permissions', sa.Integer(), nullable=True),
    sa.Column('agent_instance_type', sa.String(), nullable=True),
    sa.Column('agent_api_url', sa.String(), nullable=True),
    sa.Column('agent_api_key', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('agent_timeout', sa.Integer(), nullable=True),
    sa.Column('agent_stream_mode', sa.Boolean(), nullable=False),
    sa.Column('default_agent', sa.String(), nullable=True),
    sa.Column('automagik_instance_id', sa.String(), nullable=True),
    sa.Column('automagik_instance_name', sa.String(), nullable=True),
    sa.Column('profile_name', sa.String(), nullable=True),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('owner_jid', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('enable_auto_split', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_configs_id'), 'instance_configs', ['id'], unique=False)
    op.create_index(op.f('ix_instance_configs_is_active'), 'instance_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_instance_configs_is_default'), 'instance_configs', ['is_default'], unique=False)
    op.create_index(op.f('ix_instance_configs_name'), 'instance_configs', ['name'], unique=True)
    op.create_table('access_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rule_type IN ('allow', 'block')", name='ck_access_rules_rule_type'),
    sa.ForeignKeyConstraint(['instance_name'], ['instance_configs.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_name', 'phone_number', 'rule_type', name='uq_access_rules_scope_phone_rule')
    )
    op.create_index(op.f('ix_access_rules_id'), 'access_rules', ['id'], unique=False)
    op.create_index(op.f('ix_access_rules_instance_name'), 'access_rules', ['instance_name'], unique=False)
    op.create_index(op.f('ix_access_rules_phone_number'), 'access_rules', ['phone_number'], unique=False)
    op.create_table('setting_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['setting_id'], ['global_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_change_history_changed_at'), 'setting_change_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_setting_change_history_id'), 'setting_change_history', ['id'], unique=False)
    op.create_index(op.f('ix_setting_change_history_setting_id'), 'setting_change_history', ['setting_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('whatsapp_jid', sa.String(), nullable=False),
    sa.Column('instance_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('last_session_name_interaction', sa.String(), nullable=True),
    sa.Column('last_agent_user_id', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_name'], ['instance_configs.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_instance_name'), 'users', ['instance_name'], unique=False)
    op.create_index(op.f('ix_users_last_seen_at'), 'users', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_users_last_session_name_interaction'), 'users', ['last_session_name_interaction'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_whatsapp_jid'), 'users', ['whatsapp_jid'], unique=False)
    op.create_table('message_traces',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('instance_name', sa.String(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(), nullable=True),
    sa.Column('sender_phone', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('sender_jid', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=True),
    sa.Column('has_quoted_message', sa.Boolean(), nullable=True),
    sa.Column('message_length', sa.Integer(), nullable=True),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('agent_session_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('agent_request_at', sa.DateTime(), nullable=True),
    sa.Column('agent_response_at', sa.DateTime(), nullable=True),
    sa.Column('evolution_send_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stage', sa.String(), nullable=True),
    sa.Column('blocked_by_access_rule', sa.Boolean(), nullable=True),
    sa.Column('access_rule_id', sa.Integer(), nullable=True),
    sa.Column('blocking_reason', sa.String(), nullable=True),
    sa.Column('agent_processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('total_processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('agent_request_tokens', sa.Integer(), nullable=True),
    sa.Column('agent_response_tokens', sa.Integer(), nullable=True),
    sa.Column('agent_response_success', sa.Boolean(), nullable=True),
    sa.Column('agent_response_length', sa.Integer(), nullable=True),
    sa.Column('agent_tools_used', sa.Integer(), nullable=True),
    sa.Column('evolution_response_code', sa.Integer(), nullable=True),
    sa.Column('evolution_success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['access_rule_id'], ['access_rules.id'], ),
    sa.ForeignKeyConstraint(['instance_name'], ['instance_configs.name'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_message_traces_blocked_by_access_rule'), 'message_traces', ['blocked_by_access_rule'], unique=False)
    op.create_index(op.f('ix_message_traces_instance_name'), 'message_traces', ['instance_name'], unique=False)
    op.create_index(op.f('ix_message_traces_received_at'), 'message_traces', ['received_at'], unique=False)
    op.create_index(op.f('ix_message_traces_sender_phone'), 'message_traces', ['sender_phone'], unique=False)
    op.create_index(op.f('ix_message_traces_session_name'), 'message_traces', ['session_name'], unique=False)
    op.create_index(op.f('ix_message_traces_status'), 'message_traces', ['status'], unique=False)
    op.create_index(op.f('ix_message_traces_trace_id'), 'message_traces', ['trace_id'], unique=False)
    op.create_index(op.f('ix_message_traces_whatsapp_message_id'), 'message_traces', ['whatsapp_message_id'], unique=False)
    op.create_table('user_external_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('instance_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_name'], ['instance_configs.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', 'instance_name', name='uq_user_external_provider_instance')
    )
    op.create_index(op.f('ix_user_external_ids_external_id'), 'user_external_ids', ['external_id'], unique=False)
    op.create_index(op.f('ix_user_external_ids_id'), 'user_external_ids', ['id'], unique=False)
    op.create_index(op.f('ix_user_external_ids_instance_name'), 'user_external_ids', ['instance_name'], unique=False)
    op.create_index(op.f('ix_user_external_ids_provider'), 'user_external_ids', ['provider'], unique=False)
    op.create_index(op.f('ix_user_external_ids_user_id'), 'user_external_ids', ['user_id'], unique=False)
    op.create_table('trace_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('payload_type', sa.String(), nullable=True),
    sa.Column('payload_compressed', sa.Text(), nullable=True),
    sa.Column('payload_size_original', sa.Integer(), nullable=True),
    sa.Column('payload_size_compressed', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('contains_media', sa.Boolean(), nullable=True),
    sa.Column('contains_base64', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['message_traces.trace_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_payloads_stage'), 'trace_payloads', ['stage'], unique=False)
    op.create_index(op.f('ix_trace_payloads_timestamp'), 'trace_payloads', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trace_payloads_trace_id'), 'trace_payloads', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_payloads_trace_id'), table_name='trace_payloads')
    op.drop_index(op.f('ix_trace_payloads_timestamp'), table_name='trace_payloads')
    op.drop_index(op.f('ix_trace_payloads_stage'), table_name='trace_payloads')
    op.drop_table('trace_payloads')
    op.drop_index(op.f('ix_user_external_ids_user_id'), table_name='user_external_ids')
    op.drop_index(op.f('ix_user_external_ids_provider'), table_name='user_external_ids')
    op.drop_index(op.f('ix_user_external_ids_instance_name'), table_name='user_external_ids')
    op.drop_index(op.f('ix_user_external_ids_id'), table_name='user_external_ids')
    op.drop_index(op.f('ix_user_external_ids_external_id'), table_name='user_external_ids')
    op.drop_table('user_external_ids')
    op.drop_index(op.f('ix_message_traces_whatsapp_message_id'), table_name='message_traces')
    op.drop_index(op.f('ix_message_traces_trace_id'), table_name='message_traces')
    op.drop_index(op.f('ix_message_traces_status'), table_name='message_traces')
    op.drop_index(op.f('ix_message_traces_session_name'), table_name='message_traces')
    op.drop_index(op.f('ix_message_traces_sender_phone'), table_name='message_traces')
    op.drop_index(op.f('ix_message_traces_received_at'), table_name='message_traces')
    op.drop_index(op.f('ix_message_traces_instance_name'), table_name='message_traces')
    op.drop_index(op.f('ix_message_traces_blocked_by_access_rule'), table_name='message_traces')
    op.drop_table('message_traces')
    op.drop_index(op.f('ix_users_whatsapp_jid'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_last_session_name_interaction'), table_name='users')
    op.drop_index(op.f('ix_users_last_seen_at'), table_name='users')
    op.drop_index(op.f('ix_users_instance_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_setting_change_history_setting_id'), table_name='setting_change_history')
    op.drop_index(op.f('ix_setting_change_history_id'), table_name='setting_change_history')
    op.drop_index(op.f('ix_setting_change_history_changed_at'), table_name='setting_change_history')
    op.drop_table('setting_change_history')
    op.drop_index(op.f('ix_access_rules_phone_number'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_instance_name'), table_name='access_rules')
    op.drop_index(op.f('ix_access_rules_id'), table_name='access_rules')
    op.drop_table('access_rules')
    op.drop_index(op.f('ix_instance_configs_name'), table_name='instance_configs')
    op.drop_index(op.f('ix_instance_configs_is_default'), table_name='instance_configs')
    op.drop_index(op.f('ix_instance_configs_is_active'), table_name='instance_configs')
    op.drop_index(op.f('ix_instance_configs_id'), table_name='instance_configs')
    op.drop_table('instance_configs')
    op.drop_index(op.f('ix_global_settings_key'), table_name='global_settings')
    op.drop_index(op.f('ix_global_settings_id'), table_name='global_settings')
    op.drop_index(op.f('ix_global_settings_category'), table_name='global_settings')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
