"""Initial database schema

Revision ID: be1e23d77eed
Revises: 
Create Date: 2025-07-10 13:22:24.352224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1e23d77eed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create instance_configs table
    op.create_table('instance_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('channel_type', sa.String(), nullable=False),
        sa.Column('evolution_url', sa.String(), nullable=True),
        sa.Column('evolution_key', sa.String(), nullable=True),
        sa.Column('whatsapp_instance', sa.String(), nullable=True),
        sa.Column('session_id_prefix', sa.String(), nullable=True),
        sa.Column('webhook_base64', sa.Boolean(), nullable=False),
        sa.Column('agent_api_url', sa.String(), nullable=False),
        sa.Column('agent_api_key', sa.String(), nullable=False),
        sa.Column('default_agent', sa.String(), nullable=False),
        sa.Column('agent_timeout', sa.Integer(), nullable=True),
        sa.Column('automagik_instance_id', sa.String(), nullable=True),
        sa.Column('automagik_instance_name', sa.String(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_configs_id'), 'instance_configs', ['id'], unique=False)
    op.create_index(op.f('ix_instance_configs_is_active'), 'instance_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_instance_configs_is_default'), 'instance_configs', ['is_default'], unique=False)
    op.create_index(op.f('ix_instance_configs_name'), 'instance_configs', ['name'], unique=True)
    
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=False),
        sa.Column('whatsapp_jid', sa.String(), nullable=False),
        sa.Column('instance_name', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=True),
        sa.Column('last_session_name_interaction', sa.String(), nullable=True),
        sa.Column('last_agent_user_id', sa.String(), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(), nullable=True),
        sa.Column('message_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['instance_name'], ['instance_configs.name'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_instance_name'), 'users', ['instance_name'], unique=False)
    op.create_index(op.f('ix_users_last_seen_at'), 'users', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_users_last_session_name_interaction'), 'users', ['last_session_name_interaction'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_whatsapp_jid'), 'users', ['whatsapp_jid'], unique=False)
    
    # Create telemetry_traces table
    op.create_table('telemetry_traces',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('trace_type', sa.String(), nullable=False),
        sa.Column('operation_type', sa.String(), nullable=False),
        sa.Column('instance_name', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('session_id', sa.String(), nullable=True),
        sa.Column('agent_name', sa.String(), nullable=True),
        sa.Column('request_payload', sa.Text(), nullable=True),
        sa.Column('response_payload', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('duration_ms', sa.Float(), nullable=True),
        sa.Column('metadata', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_traces_agent_name'), 'telemetry_traces', ['agent_name'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_id'), 'telemetry_traces', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_instance_name'), 'telemetry_traces', ['instance_name'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_operation_type'), 'telemetry_traces', ['operation_type'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_session_id'), 'telemetry_traces', ['session_id'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_timestamp'), 'telemetry_traces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_trace_type'), 'telemetry_traces', ['trace_type'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_user_id'), 'telemetry_traces', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_traces_user_id'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_trace_type'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_timestamp'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_session_id'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_operation_type'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_instance_name'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_id'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_agent_name'), table_name='telemetry_traces')
    op.drop_table('telemetry_traces')
    op.drop_index(op.f('ix_users_whatsapp_jid'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_last_session_name_interaction'), table_name='users')
    op.drop_index(op.f('ix_users_last_seen_at'), table_name='users')
    op.drop_index(op.f('ix_users_instance_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_instance_configs_name'), table_name='instance_configs')
    op.drop_index(op.f('ix_instance_configs_is_default'), table_name='instance_configs')
    op.drop_index(op.f('ix_instance_configs_is_active'), table_name='instance_configs')
    op.drop_index(op.f('ix_instance_configs_id'), table_name='instance_configs')
    op.drop_table('instance_configs')
    # ### end Alembic commands ###